# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: cc ci

on:
  push:
    branches: [cc]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [cc]
jobs:
  test:
    strategy:
      matrix:
        java: ['11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Install CLD2
        run: |
          sudo apt-get update
          sudo apt-get install libcld2-0 libcld2-dev
      - name: Install language-detection-cld2
        run: |
          git clone https://github.com/commoncrawl/language-detection-cld2.git
          cd language-detection-cld2/
          mvn install
      - name: Install crawler-commons development version
        run: |
          git clone https://github.com/crawler-commons/crawler-commons.git
          cd crawler-commons/
          mvn install
      - name: Install recent public suffix list
        run: |
          curl https://publicsuffix.org/list/public_suffix_list.dat -o conf/effective_tld_names.dat
      - name: Test
        run: ant clean test -buildfile build.xml
